### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by yaroslavr-itd**
Conversions moved to routes.py

### CODE REVIEW

**Comment by israellevin** [comment]
Dude! You brought back paket.py! It's supposed to be in paket_stellar package!

**Comment by yaroslavr-itd** [comment]
Fixed that.
All tests passed for me.
Note that you need latest util version from stroops-conversion branch

**Comment by israellevin** [comment]
@yaroslavr-itd , you have to remove `paket.py` from this repository. All this functionality should be in the paket-stellar package, that's what we created if for. Please:
`git rm paket.py`.

**Comment by yaroslavr-itd** [comment]
```$ git rm paket.py
fatal: pathspec 'paket.py' did not match any files
```

Also, i don't understand why you asking this, because API uses paket-stellar package

**Pull request merged**
